In [7]:
new_nd = numpy.arange([6:100:4], dtype=None) 
new_nd

SyntaxError: invalid syntax (Temp/ipykernel_14200/4040582247.py, line 1)

In [8]:
import numpy as np
np.arange(start=6, stop=100, step=4)

array([ 6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66, 70,
       74, 78, 82, 86, 90, 94, 98])

In [9]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
print(a)

[ 1.  2.  3. nan  5.  6.  7. nan]


In [13]:
import numpy as np
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a= a[np.array.logical_not(np.array.isnan(a))]
print (a)

AttributeError: 'builtin_function_or_method' object has no attribute 'logical_not'

In [15]:
import math
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
print ([value for value in a if not math.isnan(value)])

[1.0, 2.0, 3.0, 5.0, 6.0, 7.0]


In [16]:
import numpy as np
rand_int = np.random.randint(1,100,(5,6))

In [17]:
import numpy as np
rand_int = np.random.randint(1,100,(5,6))
print(rand_int)

[[69 10 85  7 74 43]
 [64 44 65 18 16 18]
 [13 77 24 25 93 18]
 [52 69 23 36 50 81]
 [15 99  3  3 89 53]]


In [18]:
import numpy as np
rand_int = np.random.randint(1,100,(5,6))
print(rand_int)
maxInColumns = numpy.amax(rand_int, axis=0)
print(maxInColumns)

[[64 56 51  9 45  9]
 [65 30 19 83 16 43]
 [11  8 96 71 40 75]
 [30 57 58 90 50 92]
 [31 21 31 85  1 42]]


NameError: name 'numpy' is not defined

In [19]:
import numpy as np
rand_int = np.random.randint(1,100,(5,6))
print(rand_int)
maxInColumns = np.amax(rand_int, axis=0)
print(maxInColumns)

[[67 56  3 51 74  4]
 [49 29 38 19 44 26]
 [33 54 20 45 17 26]
 [54 24 27 82 48 25]
 [99  6 52 72 34 60]]
[99 56 52 82 74 60]


In [20]:
import pandas as pd
series = pd.Series(np.take(list('abcdefghijklmnop'), np.random.randint(16, size=500)))
print(series)

0      e
1      h
2      k
3      d
4      n
      ..
495    j
496    h
497    n
498    o
499    d
Length: 500, dtype: object


In [21]:
import pandas as pd
series = pd.Series(np.take(list('abcdefghijklmnop'), np.random.randint(16, size=500)))
print(series.value_counts())

k    40
l    39
c    37
a    36
p    34
b    34
m    33
g    33
o    32
f    32
i    30
j    27
d    26
n    25
e    24
h    18
dtype: int64


In [22]:
import pandas as pd
from dateutil.parser import parse
series = pd.Series(['01 Jan 2020', '10-19-2020', '20150303', '2013/04/04', '2012-05-05', '2013-06-06T12:20'])
series = series.map(lambda x: parse(x))
print("Day of month:")
print(series.dt.day.tolist())
print("Day of year:")
print(series.dt.dayofyear.tolist())
print("Week number:")
print(series.dt.weekofyear.tolist())
print("Day of week:")
print(series.dt.weekday_name.tolist())

Day of month:
[1, 19, 3, 4, 5, 6]
Day of year:
[1, 293, 62, 94, 126, 157]
Week number:
[1, 43, 10, 14, 18, 23]
Day of week:

C:\Users\FAYGAS~1\AppData\Local\Temp/ipykernel_14200/874552503.py:10: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  print(series.dt.weekofyear.tolist())


AttributeError: 'DatetimeProperties' object has no attribute 'weekday_name'

In [28]:
import pandas as pd
df = pd.read_csv(https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv)
print(df)

SyntaxError: invalid syntax (Temp/ipykernel_14200/1264485031.py, line 2)

In [41]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df)

   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Manufacturer        89 non-null     object 
 1   Model               92 non-null     object 
 2   Type                90 non-null     object 
 3   Min.Price           86 non-null     float64
 4   Price               91 non-null     float64
 5   Max.Price           88 non-null     float64
 6   MPG.city            84 non-null     float64
 7   MPG.highway         91 non-null     float64
 8   AirBags             87 non-null     object 
 9   DriveTrain          86 non-null     object 
 10  Cylinders           88 non-null     object 
 11  EngineSize          91 non-null     float64
 12  Horsepower          86 non-null     float64
 13  RPM                 90 non-null     float64
 14  Rev.per.mile        87 non-null     float64
 15  Man.trans.avail     88 non-null     object 
 16  Fuel.tank.

In [43]:
df.rename(columns={"Type": "TypeOfCar"})

Manufacturer    Model TypeOfCar  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra     Small       12.9   15.9       18.8      25.0   
1           NaN   Legend   Midsize       29.2   33.9       38.7      18.0   
2          Audi       90   Compact       25.9   29.1       32.3      20.0   
3          Audi      100   Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i   Midsize        NaN   30.0        NaN      22.0   
..          ...      ...       ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan       Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat   Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado    Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240   Compact       21.8   22.7       23.5      21.0   
92          NaN      850   Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                None      Front  ...        7.0   187.0   
89         30.0                None      Front  ...        5.0   180.0   
90         25.0                None      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [44]:
df.isna().sum()

Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

In [45]:
df.drop(columns=['EngineSize', 'Length'])

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Fuel.tank.capacity  \
0          31.0                None      Front  ...               13.2   
1          25.0  Driver & Passenger      Front  ...               18.0   
2          26.0         Driver only      Front  ...               16.9   
3          26.0  Driver & Passenger        NaN  ...               21.1   
4          30.0                 NaN       Rear  ...               21.1   
..          ...                 ...        ...  ...                ...   
88         21.0                None      Front  ...               21.1   
89         30.0                None      Front  ...               18.5   
90         25.0                None      Front  ...               18.5   
91         28.0         Driver only       Rear  ...               15.8   
92         28.0  Driver & Passenger      Front  ...               19.3   

    Passengers  Wheelbase  Width Turn.circle  Rear.seat.room  Luggage.room  \
0          5.0      102.0   68.0        37.0            26.5           NaN   
1          5.0      115.0   71.0        38.0            30.0          15.0   
2          5.0      102.0   67.0        37.0            28.0          14.0   
3          6.0      106.0    NaN        37.0            31.0          17.0   
4          4.0      109.0   69.0        39.0            27.0          13.0   
..         ...        ...    ...         ...             ...           ...   
88         7.0      115.0   72.0        38.0            34.0           NaN   
89         5.0      103.0   67.0        35.0            31.5          14.0   
90         4.0       97.0   66.0        36.0            26.0          15.0   
91         5.0      104.0   67.0        37.0            29.5          14.0   
92         5.0      105.0   69.0        38.0            30.0          15.0   

    Weight   Origin                Make  
0   2705.0  non-USA       Acura Integra  
1   3560.0  non-USA        Acura Legend  
2   3375.0  non-USA             Audi 90  
3   3405.0  non-USA            Audi 100  
4   3640.0  non-USA            BMW 535i  
..     ...      ...                 ...  
88  3960.0      NaN  Volkswagen Eurovan  
89  2985.0  non-USA   Volkswagen Passat  
90  2810.0  non-USA  Volkswagen Corrado  
91  2985.0  non-USA           Volvo 240  
92  3245.0  non-USA           Volvo 850  

[93 rows x 25 columns]

In [46]:
df.isna().sum().max()

19

In [47]:
import numpy as np

df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})
print(df1,df2)

    fruit  weight  price
0   apple    high      3
1  banana  medium      8
2  orange     low     13
3   apple    high      0
4  banana  medium      3
5  orange     low     14
6   apple    high      6
7  banana  medium     13
8  orange     low      4    pazham  kilo  price
0   apple  high     11
1  orange   low      2
2    pine  high     11
3   apple   low      6
4  orange  high      8
5    pine   low      5


In [48]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})
df1.merge(df2,left_on=('fruit','weight'),right_on=('pazham','kilo'),how='inner',suffixes=('_left','_right')).head(10)

fruit weight  price_left  pazham  kilo  price_right
0   apple   high           9   apple  high           10
1   apple   high           2   apple  high           10
2   apple   high          13   apple  high           10
3  orange    low           6  orange   low            5
4  orange    low          13  orange   low            5
5  orange    low          14  orange   low            5

In [74]:
import pandas as pd
import numpy as np
df = pd.DataFrame(["STD,City\tState",
"33,Kolkata\tWest Bengal",
"44,Chennai\tTamil Nadu",
"40,Hyderabad\tTelengana",
"80,Bangalore\tKarnataka"], columns=['row'])
df


row
0          STD,City\tState
1  33,Kolkata\tWest Bengal
2   44,Chennai\tTamil Nadu
3  40,Hyderabad\tTelengana
4  80,Bangalore\tKarnataka

In [75]:
df['row'].str.split(',', expand=True)

0                     1
0  STD           City\tState
1   33  Kolkata\tWest Bengal
2   44   Chennai\tTamil Nadu
3   40  Hyderabad\tTelengana
4   80  Bangalore\tKarnataka

In [7]:
import pandas as pd
import numpy as np

names = ["mpg", "cylinders", "displacement", "horsepower", "weight", "acceleration", "model_year", "origin", "car_name"]
df_mpg = pd.read_csv("auto-mpg.data", header=None, names=names, delim_whitespace=True)
print(df_mpg)


FileNotFoundError: [Errno 2] No such file or directory: 'auto-mpg.data'